// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKwNcVdRlLgEiCgsMOnRiEPNj91_zC4_0',
    appId: '1:639837639391:web:1191eb49d4fa74cb8f4f6a',
    messagingSenderId: '639837639391',
    projectId: 'split-b90b1',
    authDomain: 'split-b90b1.firebaseapp.com',
    storageBucket: 'split-b90b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu2XOMAyqKWRWvd3V9ue5ph4TahfL-Mno',
    appId: '1:639837639391:android:fe7ee166dbacb7fa8f4f6a',
    messagingSenderId: '639837639391',
    projectId: 'split-b90b1',
    storageBucket: 'split-b90b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmZEVuy1pk2zWOif6x7_eYomT_f1bb52A',
    appId: '1:639837639391:ios:2491763298884f928f4f6a',
    messagingSenderId: '639837639391',
    projectId: 'split-b90b1',
    storageBucket: 'split-b90b1.appspot.com',
    iosBundleId: 'com.example.split',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmZEVuy1pk2zWOif6x7_eYomT_f1bb52A',
    appId: '1:639837639391:ios:2491763298884f928f4f6a',
    messagingSenderId: '639837639391',
    projectId: 'split-b90b1',
    storageBucket: 'split-b90b1.appspot.com',
    iosBundleId: 'com.example.split',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKwNcVdRlLgEiCgsMOnRiEPNj91_zC4_0',
    appId: '1:639837639391:web:cb4476f3c60970408f4f6a',
    messagingSenderId: '639837639391',
    projectId: 'split-b90b1',
    authDomain: 'split-b90b1.firebaseapp.com',
    storageBucket: 'split-b90b1.appspot.com',
  );
}
